### ISSUE TITLE
When downloading the image in dark mode a unproper image is comming

### ISSUE THREAD

**Issue by Arnab9674** [dscnsec/logo-generator#2]

**Comment by Arnab9674** [comment]
![GDG City Name Dark Horizontal-Logo](https://user-images.githubusercontent.com/58770076/99881747-94731b00-2c41-11eb-8a14-0f0a915bde0d.png)
Here is the image

**Comment by Arnab9674** [comment]
![ice_screenshot_20201121-203427](https://user-images.githubusercontent.com/58770076/99881779-cbe1c780-2c41-11eb-8c55-f49cda4afd7d.png)
Here is the screen shot after downloading the image

**Comment by sairish2001** [comment]
This is Because Your Image Viewer's Background is White and Logo Color is also White in color. That's why the logo is not visible to you.

**Comment by sairish2001** [comment]
![image](https://user-images.githubusercontent.com/60106112/100519336-4029e700-31bd-11eb-9133-646b9276884f.png)
see this , I am using my windows in dark mode.
